### PR TITLE
Add 4x and 8x playback speeds

### PR DESCRIPTION
**Pull request by ElementalAlchemist**

### CODE REVIEW

**Review by ekimekim — APPROVED** [review]
Any chance you could make num + still go to 2x? Otherwise my muscle memory will kill me when skipping through.

**Comment by ElementalAlchemist** [comment]
Should we say Shift+= is now 2x speed and not max speed? Or should we dedicate a new keyboard shortcut to it?

**Comment by ekimekim** [comment]
Going to 2x would be my preference, since there's lots of levels between 1x and 2x but very few between 2x and higher. We could make the same button go to max if it's already >= 2x?

**Comment by ElementalAlchemist** [comment]
I liked your last suggestion, so I have done that.

**Review by ekimekim — APPROVED** [review]

**Pull request merged**
